import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

// Configure the local fonts
const poppins = localFont({
	src: [
		{
			path: "../../public/fonts/poppins/poppins-v22-latin-300.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "../../public/fonts/poppins/poppins-v22-latin-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/poppins/poppins-v22-latin-600.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../../public/fonts/poppins/poppins-v22-latin-700.woff2",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-poppins",
});

const sourceCodePro = localFont({
	src: [
		{
			path: "../../public/fonts/source-code-pro/source-code-pro-v23-latin-regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/source-code-pro/source-code-pro-v23-latin-500.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../../public/fonts/source-code-pro/source-code-pro-v23-latin-600.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../../public/fonts/source-code-pro/source-code-pro-v23-latin-700.woff2",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-source-code-pro",
});

export const metadata: Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className={`${poppins.variable} ${sourceCodePro.variable}`}>
			<body>
				<SidebarProvider>
					<AppSidebar />
					<main>
						<SidebarTrigger />
						{children}
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
